### ISSUE TITLE
Using rioxarray paralell read

### ISSUE THREAD

**Issue by parevalo** [nasa/HLS-Data-Resources#30]
Is there any significant reason to not use the parallel read offered by rioxarray (i.e. lock=False) in the examples provided in the HLS Python tutorial? It would significantly speed up the code. If parallel read through that option is ok, are there any recommendations or guidelines to use that option responsibly?

**Comment by ebolch** [comment]
Just reposting this from the Earthdata Forum in case its helpful to someone else:

The example HLS tutorial we created doesn't utilize the `lock=False` option but using it should be fine. Instead of using cookies, we recommend the `GDAL_HTTP_AUTH='BEARER'` configuration option.

Some other additional considerations for HLS are:

- You may want to increase chunk size from 512x512 to 3600x3600 (full scene) depending on how large a region of interest is. If all the data from a scene is needed, using the full scene size rather than the internal tile chunk size will improve performance.
- If you want to stack HLS Landsat and HLS Sentinel scenes, you'll have to handle the difference in quantity and naming convention of the bands.
- There's a known issue with some HLS Landsat scenes, where the scale_factor is in the general file metadata, not the band level metadata. Because of this, occasionally some scenes may not scale properly with `mask_and_scale=True` using `rioxarray`.

I made a [short jupyter notebook](https://forum.earthdata.nasa.gov/viewtopic.php?t=6231#confirm_external_link-modal) of how I would approach this. If you're doing something more performant, please share.
